### ISSUE TITLE
Pierwszy issue - Readme.md

### ISSUE THREAD

**Issue by Cosiek** [Bialka/cokolwiek#1]
Pierwsze zadanie, do wstępnego zaznajomienia się z obsługą git-a i githuba ( :octocat: ).

 - sprawdź czy masz zainstalowanego git-a (w konsoli wpisz `git` - jeśli powie, że nie zna takiego polecenia, to musisz go zainstalować)
 - jeśli nie, to zainstaluj (do pobrania tu - `https://git-scm.com/`, choć może lepiej będzie, jak zainstalujesz sobie program z graficznym interfejsem użytkownika - np. stąd: `https://desktop.github.com/`)
 - sklonuj sobie repozytorium (przejdź w konsoli do katalogu w którym chcesz trzymać kod `cd C:\przykladowa\sciezka` i wpisz `git clone https://github.com/Bialka/cokolwiek.git`)
 - utwórz w nim plik - nazwij go readme.md (możesz użyć notatnika)
 - w treści wpisz tylko `# cokolwiek`
 - zestaguj plik (`git add readme.md`)
 - skomituj plikt (`git commit -m "Add Readme"`)
 - wypchnij ten plik (`git push`)
 - sprawdź czy pojawił się na githubie (tu: https://github.com/Bialka/cokolwiek)

Sporą część tych rzeczy pewnie wygodniej będzie Ci zrobić przez program z interfejsem, więc nie musisz się jakoś kurczowo trzymać tych instrukcji.

**Comment by Bialka** [comment]
Ok, chyba się udało. Co teraz?

**Comment by Cosiek** [comment]
Nie udało się. Plik nie dotarł na githuba.
Czy po wpisaniu którejś z tych komend nie wyświetlił Ci się komunikat o błędzie?

**Comment by Bialka** [comment]
Nie wyświetlił mi się żaden błąd.

**Comment by Bialka** [comment]
A teraz jest?

**Comment by Cosiek** [comment]
Teraz jest :+1: 
Zamykam issue.
