### ISSUE TITLE
Zmiana formy zapisu linijek w pliku.

### ISSUE THREAD

**Issue by Cosiek** [Bialka/cokolwiek#14]
W tej chwili treść pliku `cokolwiek.txt` wygląda mniej więcej tak:
```
do_zrobienia/Mosaic
do_zrobienia/Born to Be Blue
do_zrobienia/Nowy/Phantom Doctrine
do_zrobienia/A Prominent Patient (Masaryk)
do_zrobienia/Samba
do_zrobienia/Picnic at Hanging Rock
do_zrobienia/Free the Mind
```

A chciałbym, żeby wyglądał tak:
```
 - | do_zrobienia/Tonight She Comes                     |  12
 - | do_zrobienia/Valley of Shadows                     |  14
 - | do_zrobienia/Free the Mind                         |  17
 - | do_zrobienia/Pora Umierac [Time to Die]            |  31
 - | do_zrobienia/Nowy/Into the Unknown                 |   4
```

Czyli:
 - na początku każdej linijki dodajesz " - | "
 - każda linijka przewiduje 50 znaków na nazwę katalogu
 - do każdej linijki dodany jest przerywacz "|  "
 - do każdej linijki dopisana jest liczba plików w katalogu

Sztuczki,które pomogą Ci to wszystko wykonać:

 - Przy zapisie słownika do pliku zamiast iterować po kluczach (`for klucz, pliki in slownik.keys():`), iteruj po itemach (`for klucz, pliki in slownik.items():`)
 - Policzyć pliki na liście możesz przy pomocy funkcji `len(pliki)` (ogólnie len to bardzo przydatna funkcja)
 - Wygodnie będzie Ci użyć [funkcji format](https://docs.python.org/3/library/string.html#format-specification-mini-language). Np. tak `" - | {0: <50}| {1: >3}".format(klucz, liczba_plikow)`

P.S. - dobrze by było, gdybyś poczytała sobie coś o działaniu funkcji format w pythonie.

**Comment by Bialka** [comment]
Zmieniłam i wypchnęłam.

**Comment by Cosiek** [comment]
Działa :+1:
