### ISSUE TITLE
Coś zrobić z odczytem

### ISSUE THREAD

**Issue by Cosiek** [Bialka/cokolwiek#15]
Mamy już zebrane trochę danych o tym co siedzi w naszych katalogach.
Czas zacząć modyfikować zawartość, zamiast tylko odczytywać dane.

Obecnie program po pierwszym uruchomieniu tworzy plik o nazwie `cokolwiek.txt` i zapisuje w nim listę podkatalogów zawierających pliki mp3.

Skoro po pierwszym uruchomieniu programu mam taki plik, to mogę go modyfikować ręcznie. Mogę na przykład wskazać, które katalogi chcę usunąć.

Jeżeli więc mam plik o takiej zawartości:
```
 - | do_zrobienia/Mandy                                |  15
 - | do_zrobienia/GlobalPlayer/Global Player           |  15
 - | do_zrobienia/VICE                                 |  26
```
i chcę usunąć katalogi "Mandy" i "VICE", to zmienię początkową kreskę na literkę "u" (jak usuń). Czyli plik po edycji będzie wyglądał tak:
```
 u | do_zrobienia/Mandy                                |  15
 - | do_zrobienia/GlobalPlayer/Global Player           |  15
 u | do_zrobienia/VICE                                 |  26
```

Zadanie polega na tym, żeby przy drugim uruchomieniu programu, odczytać kolejne linijki pliku i zadziałać zgodnie z tym co jest napisane. Więc, jeśli linijka zaczyna się od ` - `, to nic nie robimy, ale jeśli zaczyna się od ` u `, to usuwamy wskazany katalog z dysku.

## wskazówki

 - masz już odczyt pliku, trzeba tylko przeiterować po linijkach. Możesz skorzystać albo z `f.readline()` (wskazówek jak to zrobić szukaj w góglach), albo `for ln in x.split("\n"):`
 - przyda Ci się funkcja `.split()`, która jest metodą stringów. Dzięki temu będziesz mogła rozdzielić linijkę na poszczególne części, rozcinając je na znaku "|" - `ln.split("|")`
 - pomocna może się też okazać metoda `.strip()`, również na stringach, Dzięki niej pozbędziesz się zbędnych białych znaków (spacji).
 - Tutaj masz wskazówkę jak możesz usuwać katalogi `https://stackoverflow.com/a/303225/3362530`

Później w analogiczny sposób jak usuwanie, będziemy oznaczać katalogi do edycji.

**Comment by Bialka** [comment]
``
  with open(sciezka_pliku, 'r') as f:
            x = f.read()
            for ln in x.split("\n"):
                ln = x.split("|")
                print(ln)
``
Mam coś takiego i daje to taki wynik:
``
[' - ', ' do_zrobienia\\3                                    ', '   3', '\n - ', ' do_zrobienia\\1\\1.2
           ', '   5', '\n - ', ' do_zrobienia\\2\\2.1                                ', '   5', '\n - ', ' do_zrobienia\\1\\
1.1                                ', '   4', '\n - ', ' do_zrobienia\\2\\2.2                                ', '   4', '\n
- ', ' do_zrobienia\\5                                    ', '   5', '\n - ', ' do_zrobienia\\7
       ', '   7', '\n - ', ' do_zrobienia\\4                                    ', '   6', '\n - ', ' do_zrobienia\\6
                             ', '   3', '\n']
[' - ', ' do_zrobienia\\3                                    ', '   3', '\n - ', ' do_zrobienia\\1\\1.2
           ', '   5', '\n - ', ' do_zrobienia\\2\\2.1                                ', '   5', '\n - ', ' do_zrobienia\\1\\
1.1                                ', '   4', '\n - ', ' do_zrobienia\\2\\2.2                                ', '   4', '\n
- ', ' do_zrobienia\\5                                    ', '   5', '\n - ', ' do_zrobienia\\7
       ', '   7', '\n - ', ' do_zrobienia\\4                                    ', '   6', '\n - ', ' do_zrobienia\\6
                             ', '   3', '\n']
[' - ', ' do_zrobienia\\3                                    ', '   3', '\n - ', ' do_zrobienia\\1\\1.2
           ', '   5', '\n - ', ' do_zrobienia\\2\\2.1                                ', '   5', '\n - ', ' do_zrobienia\\1\\
1.1                                ', '   4', '\n - ', ' do_zrobienia\\2\\2.2                                ', '   4', '\n
- ', ' do_zrobienia\\5                                    ', '   5', '\n - ', ' do_zrobienia\\7
       ', '   7', '\n - ', ' do_zrobienia\\4                                    ', '   6', '\n - ', ' do_zrobienia\\6
                             ', '   3', '\n']
[' - ', ' do_zrobienia\\3                                    ', '   3', '\n - ', ' do_zrobienia\\1\\1.2
           ', '   5', '\n - ', ' do_zrobienia\\2\\2.1                                ', '   5', '\n - ', ' do_zrobienia\\1\\
1.1                                ', '   4', '\n - ', ' do_zrobienia\\2\\2.2                                ', '   4', '\n
- ', ' do_zrobienia\\5                                    ', '   5', '\n - ', ' do_zrobienia\\7
       ', '   7', '\n - ', ' do_zrobienia\\4                                    ', '   6', '\n - ', ' do_zrobienia\\6
                             ', '   3', '\n']
[' - ', ' do_zrobienia\\3                                    ', '   3', '\n - ', ' do_zrobienia\\1\\1.2
           ', '   5', '\n - ', ' do_zrobienia\\2\\2.1                                ', '   5', '\n - ', ' do_zrobienia\\1\\
1.1                                ', '   4', '\n - ', ' do_zrobienia\\2\\2.2                                ', '   4', '\n
- ', ' do_zrobienia\\5                                    ', '   5', '\n - ', ' do_zrobienia\\7
       ', '   7', '\n - ', ' do_zrobienia\\4                                    ', '   6', '\n - ', ' do_zrobienia\\6
                             ', '   3', '\n']
[' - ', ' do_zrobienia\\3                                    ', '   3', '\n - ', ' do_zrobienia\\1\\1.2
           ', '   5', '\n - ', ' do_zrobienia\\2\\2.1                                ', '   5', '\n - ', ' do_zrobienia\\1\\
1.1                                ', '   4', '\n - ', ' do_zrobienia\\2\\2.2                                ', '   4', '\n
- ', ' do_zrobienia\\5                                    ', '   5', '\n - ', ' do_zrobienia\\7
       ', '   7', '\n - ', ' do_zrobienia\\4                                    ', '   6', '\n - ', ' do_zrobienia\\6
                             ', '   3', '\n']
[' - ', ' do_zrobienia\\3                                    ', '   3', '\n - ', ' do_zrobienia\\1\\1.2
           ', '   5', '\n - ', ' do_zrobienia\\2\\2.1                                ', '   5', '\n - ', ' do_zrobienia\\1\\
1.1                                ', '   4', '\n - ', ' do_zrobienia\\2\\2.2                                ', '   4', '\n
- ', ' do_zrobienia\\5                                    ', '   5', '\n - ', ' do_zrobienia\\7
       ', '   7', '\n - ', ' do_zrobienia\\4                                    ', '   6', '\n - ', ' do_zrobienia\\6
                             ', '   3', '\n']
[' - ', ' do_zrobienia\\3                                    ', '   3', '\n - ', ' do_zrobienia\\1\\1.2
           ', '   5', '\n - ', ' do_zrobienia\\2\\2.1                                ', '   5', '\n - ', ' do_zrobienia\\1\\
1.1                                ', '   4', '\n - ', ' do_zrobienia\\2\\2.2                                ', '   4', '\n
- ', ' do_zrobienia\\5                                    ', '   5', '\n - ', ' do_zrobienia\\7
       ', '   7', '\n - ', ' do_zrobienia\\4                                    ', '   6', '\n - ', ' do_zrobienia\\6
                             ', '   3', '\n']
[' - ', ' do_zrobienia\\3                                    ', '   3', '\n - ', ' do_zrobienia\\1\\1.2
           ', '   5', '\n - ', ' do_zrobienia\\2\\2.1                                ', '   5', '\n - ', ' do_zrobienia\\1\\
1.1                                ', '   4', '\n - ', ' do_zrobienia\\2\\2.2                                ', '   4', '\n
- ', ' do_zrobienia\\5                                    ', '   5', '\n - ', ' do_zrobienia\\7
       ', '   7', '\n - ', ' do_zrobienia\\4                                    ', '   6', '\n - ', ' do_zrobienia\\6
                             ', '   3', '\n']
[' - ', ' do_zrobienia\\3                                    ', '   3', '\n - ', ' do_zrobienia\\1\\1.2
           ', '   5', '\n - ', ' do_zrobienia\\2\\2.1                                ', '   5', '\n - ', ' do_zrobienia\\1\\
1.1                                ', '   4', '\n - ', ' do_zrobienia\\2\\2.2                                ', '   4', '\n
- ', ' do_zrobienia\\5                                    ', '   5', '\n - ', ' do_zrobienia\\7
       ', '   7', '\n - ', ' do_zrobienia\\4                                    ', '   6', '\n - ', ' do_zrobienia\\6
                             ', '   3', '\n']
``
Nie wychodzi mi użycie .``strip()``, nie wiem gdzie to umieścić. Nie wychodzi mi też usuwanie katalogów. Próbowałam z pętlą:
``
        with open(sciezka_pliku, 'r') as f:
            x = f.read()
            for ln in x.split("\n"):
                ln = x.split("|")
                if ln == "u":
                    shutil.rmtree("/folder_name", ignore_errors=True)
                print(ln)
``
ale nie działa. Mogę więcej wskazówek?

**Comment by Bialka** [comment]
```
with open(sciezka_pliku, 'r') as f:
            x = f.read()
            for ln in x.split("\n"):
                ln = x.split("|")
                print(ln)
```
Mam coś takiego. Nie wychdzi mi użycie ```.strip()```, nie wiem gdzie to umieścić. Nie wychodzi mi też usuwanie katalogów, próbowałam z pętlą, ale nie działa.
```
 with open(sciezka_pliku, 'r') as f:
            x = f.read()
            for ln in x.split("\n"):
                ln = x.split("|")
                if ln == "u":
                    shutil.rmtree("/folder_name", ignore_errors=True)
                print(ln)
```
Mogę więcej wskazówek?

**Comment by Bialka** [comment]
Wszystko wypchnięte.

**Comment by Cosiek** [comment]
Wygląda dobrze. Zamykam issue i biorę się za pisanie kolejnego.
