### ISSUE TITLE
Przeniesienie plików do "zrobione"

### ISSUE THREAD

**Issue by Cosiek** [Bialka/cokolwiek#16]
Analogicznie jak zamiana "-" na "u" oznacza usunięcie katalogu, wraz z zawartością, tak zamiana kreski na "p" będzie oznaczało przeniesienie wszystkich plików mp3 do odpowiedniego katalogu. 

Co to znaczy "odpowiedniego katalogu"? Na razie trochę sprawy uprościmy (potem to bedzie bardziej skomplikowane).

Powiedzmy że mam takie katalogi:
```
 - | do_zrobienia/VICE                                 |  26
 - | do_zrobienia/QueenoftheDesert/Queen of the Desert |   1
 - | do_zrobienia/Nowy/Castle Rock (Single)            |   5
 - | do_zrobienia/Nowy/Into the Unknown                |   4
```
to pliki powinny zostać przeniesione do katalogów:
```
zrobione/VICE
zrobione/Queen of the Desert
zrobione/Castle Rock (Single)
zrobione/Into the Unknown
```

Program powinien się upewnić, że katalog "zrobione" istnieje.

Po przeniesieniu plików, katalog oryginalny powinien zostać usunięty.

### wskazówki
 - zwróć uwagę, że nie ważne ile katalogów w głąb znajdują się pliki, docelowo są zawsze w katalogu który ma tę samą nazwę co najgłębszy z oryginalnych
 - właściwie możesz podejść do tematu na dwa sposoby (preferuję drugi, choć może wydawać się trudniejszy):
   - przekopiować / przenieść katalog i zmienić jego nazwę
   - utworzyć nowy katalog w lokalizacji docelowej i przenieść pliki 
 - W funkcji `zbierz_dane_o_mp3` wykorzystałaś `os.walk`, możesz z niego skorzystać jeszcze raz, tym razem podając jako `katalog` ten najgłębiej osadzony - w ten sposób przeiterujesz po plikach.
 - Użyj `.strip(os.sep)` żeby rozdzielić ścieżkę na poszczególne katalogi.
 - [Link do dokumentacji funkcji służącej do kopiowania plików](https://docs.python.org/3/library/shutil.html#shutil.copy2) (są też inne, ale ta chyba będzie tu najlepsza)
 - [Link do dokumentacji funkcji służącej do tworzenia katalogów](https://docs.python.org/3/library/os.html#os.mkdir)

**Comment by Bialka** [comment]
```
def przenoszenie_plik(obecny_katalog):
    with open(sciezka_pliku, 'r') as f:
        x = f.read().strip()
        for ln in x.split("\n"):
            ln = ln.split("|")
    a = ln[1].split("\\")
    obecny_katalog = a[1: 2]
    for x in os.walk(obecny_katalog):
        with open(x, 'r') as f:
            y = f.read()
            if ln[0].strip() == "p":
                w = y.copy2()
                shutil.move(w/file.foo, katalog_docelowy/file.foo)
    os.remove(obecny_katalog)



if __name__ == "__main__":
    print("Zaczynam")
    sciezka_pliku = 'cokolwiek.txt'
    if os.path.isfile(sciezka_pliku):
       usuwanie_kat(sciezka_pliku)
    else:
        slownik = zbierz_dane_o_mp3("do_zrobienia")
        zapis(slownik, sciezka_pliku)

    katalog_docelowy = "zrobione"
    if os.path.exists(katalog_docelowy):
        przenoszenie_plik("do_zrobienia")
    else:
        os.makedirs(katalog_docelowy)
```
Help

**Comment by Bialka** [comment]
```
def przenoszenie_plik(obecny_katalog):
    for x in os.walk(obecny_katalog):
        with open(x, 'r') as f:
            y = f.read()
            if ln[0].strip() == "p":
                w = y.copy2()
                shutil.move(w/file.foo, katalog_docelowy/file.foo)
    os.remove(obecny_katalog)



if __name__ == "__main__":
    print("Zaczynam")
    sciezka_pliku = 'cokolwiek.txt'
    if os.path.isfile(sciezka_pliku):
       obrobka_plikow(sciezka_pliku)
    else:
        slownik = zbierz_dane_o_mp3("do_zrobienia")
        zapis(slownik, sciezka_pliku)

    obecny_katalog = "do_zrobienia"
    katalog_docelowy = "zrobione"
    if not os.path.exists(katalog_docelowy):
        os.makedirs(katalog_docelowy)
```
Mam coś takiego i gdy uruchamiam program (w cokolwiek.txt wpisałam jedno "p") wyskakuje mi błąd, że "obecny_katalog" nie jest zdefiniowany.

**Comment by Cosiek** [comment]
Nie wkleiłaś funkcji `obrobka_plikow`. Podejrzewam, że w niej masz wywołanie `przenoszenie_plik(obecny_katalog)`, a tam zmienna `obecny_katalog` nie jest zdefiniowana.

Sprawdź też jak działa `os.walk` - zwraca coś innego niż Ci się wydaje.

**Comment by Bialka** [comment]
```
def przenoszenie_plik(obecny_katalog):
    obecny_katalog = "do_zrobienia"
    for x in os.walk(obecny_katalog):
        with open(x, 'r') as f:
            y = f.read()
            if ln[0].strip() == "p":
                w = y.copy2()
                shutil.move(w/file.foo, katalog_docelowy/file.foo)
    os.remove(obecny_katalog)



if __name__ == "__main__":
    print("Zaczynam")
    sciezka_pliku = 'cokolwiek.txt'
    if os.path.isfile(sciezka_pliku):
       obrobka_plikow(sciezka_pliku)
    else:
        slownik = zbierz_dane_o_mp3("do_zrobienia")
        zapis(slownik, sciezka_pliku)

    obecny_katalog = "do_zrobienia"
    katalog_docelowy = "zrobione"
    if not os.path.exists(katalog_docelowy):
        os.makedirs(katalog_docelowy)
    obrobka_plikow(sciezka_pliku)
```
Mam coś takiego i wciąż pokazuje, że ```obecny_katalog``` nie jest zdefiniowany. Mógłbyś mi wyjaśnić jak użyć ```os.walk``` w tym przypadku? Rozumiem, że może zwracać różne rzeczy, ale nie mam pomysłu jak to zastosować tutaj.

**Comment by Bialka** [comment]
```
def obrobka_plikow(sciezka_pliku):
    with open(sciezka_pliku, 'r') as f:
        x = f.read().strip()
        for ln in x.split("\n"):
            ln = ln.split("|")
            if ln[0].strip() == "u":
                shutil.rmtree(ln[1].strip(), ignore_errors=True)
            elif ln[0].strip() == "p":
                przenoszenie_plik(obecny_katalog)
            print(ln)
    os.remove(sciezka_pliku)
```

**Comment by Bialka** [comment]
```
def przenoszenie_plik(obecny_katalog):
    for x, y, z in os.walk(obecny_katalog):
        for f in z:
            shutil.move(w/file.foo, katalog_docelowy/file.foo)
    # todo: usuwanie drzewa
    os.remove(obecny_katalog)
```

**Comment by Cosiek** [comment]
Ok będzie wskazówka.
`os.walk(obecny_katalog)` zwraca krotkę (prawie to samo co lista, tyle że nie daje się modyfikować) z trzema elementami:
 - string zawierający ścieżkę do bieżącego katalogu
 - listę stringów zawierających nazwy podkatalogów
 - listę stringów zawierających nazwy plików w katalogu
W pierwszej iteracji `os.walk` katalogiem bieżącym jest ten który przekazujesz do `os.walk` jako parametr. W kontekście tej funkcji, tak naprawdę jest to jedyny który Cię interesuje. W kolejnych iteracjach, podkatalogi kolejno przyjmują funkcję katalogu głównego.

Więc:
```python
def przenoszenie_plik(obecny_katalog, katalog_docelowy):
    podkatalog_docelowy = obecny_katalog.split(os.sep)[-1]
    for x, y, z in os.walk(obecny_katalog):
        for f in z:
            source_pth = x + os.sep + f
            destination_pth = karalog_docelowy + os.sep + podkatalog_docelowy + os.sep + f
            shutil.move(source_pth, destination_pth)
        break  # bo nie chcemy wchodzić do podkatalogów
    # todo: usuwanie drzewa
```
Co do samej idei to powinno być ok, ale nie uruchamiałem tego kodu, więc nie zdziwię się, jeśli coś nie będzie działać tak jak powinno. Naprawisz.

**Comment by Bialka** [comment]
```
def przenoszenie_plik(obecny_katalog):
    podkatalog_docelowy = obecny_katalog.split(os.sep)[-1]
    for x, y, z in os.walk(obecny_katalog):
        for f in z:
            source_pth = x + os.sep + f
            destination_pth = katalog_docelowy + os.sep + podkatalog_docelowy + os.sep + f
            os.makedirs(destination_pth)
            shutil.move(source_pth, destination_pth)
        break
    # todo: usuwanie drzewa
    os.remove(obecny_katalog)
```
Mam coś takiego i odmawia mi dostępu:
```
PermissionError: [WinError 5] Odmowa dostępu: 'do_zrobienia\\7'
```
Nie znalazłam żadnego dobrego sposobu jak to naprawić.

**Comment by Cosiek** [comment]
Ok - to jest trochę dziwne. Jestem ciekaw w którym momencie to się wywala? Przy `shutil.move`, czy przy `os.remove`.

Spróbuj poszukać uprawnień do tego katalogu - "do_zrobienia\\7'". Kliknij na niego prawym przyciskiem myszy i poszukaj czegoś o uprawnieniach / właścicielu.

Wypchnij też kod - może chodzi o coś innego.

Jedno co widzę, że jest źle, to 
```
destination_pth = katalog_docelowy + os.sep + podkatalog_docelowy + os.sep + f
os.makedirs(destination_pth)
```
W tej postaci, `destination_pth` zawiera nazwę pliku (`_ os.sep + f`), a próbujesz utworzyć katalogi na 
podstawie tej zmiennej.

**Comment by Bialka** [comment]
Wywala się przy ```os.remove```.

**Comment by Bialka** [comment]
Poprawiłam ```destination_pth``` i wypchnęłam. Dalej wywala się przy ```os.remove```.

**Comment by Cosiek** [comment]
Wygląda na to, że albo musisz zmienić uprawnienia do katalogów na których działasz.
Wydaje mi się, że ten link będzie odpowiedni:
https://technikinformatyk.pl/soisk/windows-10-uprawnienia-ntfs/

**Comment by Bialka** [comment]
Sprawdziłam, mam dostęp do tych katalogów.

**Comment by Cosiek** [comment]
`os.remove` służy do usuwania plików, a nie katalogów.

Spróbuj użyć `shutil.rmtree(obecny_katalog, ignore_errors=True)`

Jeśli to nie zadziała, to odpuść usuwanie katalogu - zostaw tylko "TODO"

**Comment by Bialka** [comment]
Działa. Wypchnęłam.

**Comment by Cosiek** [comment]
Trochę słabo, że taki błąd jest opisywany jako `PermissionError`. :unamused: 
Na linuksie dostałem 'IsADirectoryError'. 

Super. Zamykam i przystępuję do pisania kolejnego issue.
