### ISSUE TITLE
Witaj świecie

### ISSUE THREAD

**Issue by Cosiek** [Bialka/cokolwiek#2]
Skoro już mamy repozytorium, to można się brać za właściwe pisanie programu.
Zacznijmy od czegoś skrajnie prostego - czyli tradycyjne "Witaj świecie".

Utwórz w repozytorium plik o nazwie cokolwiek.py i w treści wpisz kod który wyświetli tekst "Hello world!".
Jak będziesz miała gotowy plik, to w konsoli przejdź do katalogu repozytorium i wykonaj tam komendę `python cokolwiek.py`. Jeśli wszystko zadziała, skomituj plik i wyślij na githuba (`git pull`).

Jeśli coś pójdzie źle, to przeczytaj komunikat błędu i spróbuj sobie z nim poradzić.

**Comment by Bialka** [comment]
Już.

**Comment by Cosiek** [comment]
Skąd opis komita "Add files via upload"?

**Comment by Bialka** [comment]
Nie wiem. Nic nie pisałam.

**Comment by Bialka** [comment]
Co mam teraz zrobić?

**Comment by Cosiek** [comment]
Czego używasz do obsługi gita? Najwyraźniej to coś wpisało Ci z automatu komunikat.

**Comment by Bialka** [comment]
Do obsługi używam konsoli Windows PowerShell.

**Comment by Bialka** [comment]
Albo tego GitHub Deskopt, bo tak jak pisałeś nim jest łatwiej.

**Comment by Cosiek** [comment]
Zamykam.
