### ISSUE TITLE
Aktualizacja tagów przenoszonych plików

### ISSUE THREAD

**Issue by Cosiek** [Bialka/cokolwiek#28]
Skoro już tak się zdarzyło, że użytkownik wpisał nam w cokolwiek.txt jak chce żeby były zapisane nazwa albumu i wykonawca albumu, to fajnie byłoby, żeby przy przenoszeniu plików te dane były zapisywane też w tagach plików.

Więc w momencie przenoszenia pliku, chcemy, żeby tagi plików dotyczące artysty albumu i nazwy albumu były aktualizowane.

Wskazówki:
Użyć mutagenu do edycji tagów.

**Comment by Bialka** [comment]
Skończone.
