### ISSUE TITLE
Przejście po katalogach

### ISSUE THREAD

**Issue by Cosiek** [Bialka/cokolwiek#3]
W katalogu repozytorium utwórz nowy folder. Nazwij go powiedzmy "do_zrobienia".
W tym katalogu utwórz kilka podkatalogów, a w nich po kilka plików (idealnie by było, gdybyś miała pliki muzyczne mp3). W co najmniej jednym z nich, utwórz dwa podkatalogi i w nich też dodaj po kilka plików.

To będzie twój katalog z danymi testowymi. Jeśli już to zrobisz, to zobaczysz, że git widzi te pliki jako coś co należy skomitować (jako różnice w kodzie). Ponieważ nie chcemy komitować i wysyłać plików testowych, w katalogu repo dodaj plik o nazwie `.gitignore` (kropka na początku jest istotna). W tym pliku będziesz wpisywać rzeczy, które git ma ignorować. Otwórz go notatnikiem i wpisz linijkę `do_zrobienia`. Następnie skomituj plik `.gitignore`, **w opisie komita wpisz "Dodaj .gitignore"**.

**Comment by Bialka** [comment]
Mam to .gitignore wysyłać na GitHuba?

**Comment by Cosiek** [comment]
Tak.

**Comment by Bialka** [comment]
Już.

**Comment by Cosiek** [comment]
To teraz kolejny etap.
Masz wyprintować wszystkie podkatalogi które znajdują się w katalogu `do_zrobienia`.

W tym celu użyj funkcji `walk` z paczki `os`. [Tu](https://docs.python.org/3/library/os.html#os.walk) jest link do dokumentacji funkcji.

Więc:
```
import os

for x in os.walk("do_zrobienia"):
    pritn(x)
```

**Comment by Bialka** [comment]
Już, wszystko działa.

**Comment by Cosiek** [comment]
Wypchnij.

**Comment by Cosiek** [comment]
W senie do githuba (`git push`).

**Comment by Bialka** [comment]
A skomitować najpierw?

**Comment by Cosiek** [comment]
Standardowy ciąg pracy z gitem (wersja uproszczona):
 - wprowadzić zmiany w pliku
 - stage zmian (polecenie `git add`)
 - komit zmian (polecenie `git commit`, uruchomi edytor tekstu, gdzie w pierwszel linijce wpisujesz opis komita)
 - wypchnięcie zmian do zdalnego repozytorium (`git push`)

Bez skomitowania, nie wypchniesz zmian.

**Comment by Bialka** [comment]
Okej.

**Comment by Bialka** [comment]
Już jest.

**Comment by Bialka** [comment]
Nie wychodzi mi tylko to wypychanie plików przez konsolę (git push), i zamiast tego wchodzę na GitHubie w zakładkę "Code", i tam wybieram  "Upload files", ale też działa.

**Comment by Cosiek** [comment]
> Nie wychodzi mi tylko to wypychanie plików przez konsolę (git push), i zamiast tego wchodzę na GitHubie w zakładkę "Code", i tam wybieram "Upload files", ale też działa.

To źle. Co to znaczy "Nie wychodzi"? Git podaje jakiś komunikat błędu? Co mówi konsola, po tym jak wpiszesz `git push`?

Wypchnęłaś plik `nazwa.py`, podzcas gdy kod który w nim jest, powinien znaleźć się w `cokolwiek.py`.

**Comment by Bialka** [comment]
Próbowałam jeszcze raz wypchnąć plik przez konsolę, ale wyskakuje mi takie coś:
![vbbez tytulu](https://user-images.githubusercontent.com/18377128/42532411-1eda3748-8487-11e8-880f-51860bc859e8.png)

**Comment by Bialka** [comment]
A nie mam niczego innego włączonego, nawet po ponownym uruchomieniu komputera nie działa.

**Comment by Cosiek** [comment]
Wykonaj `git status` i prześlij mi wynik.
Nie powinno tak być, ale może ten program do obsługi gita z interfejsem coś blokuje.

Ostatecznie możesz wyrzucić plik `index.lock`, ale to może jak już zobaczymy `git status`.

**Comment by Bialka** [comment]
![kdcv](https://user-images.githubusercontent.com/18377128/42536346-0f278674-8492-11e8-9744-c06db68f8510.png)

**Comment by Cosiek** [comment]
Ok - dzieje się coś dziwnego. Z jakiegoś powodu rozeszłaś się z masterem na githubie (:thinking: - no tak - wysyłałaś pliki przez "upload file").
Trochę przestrzał, ale na tym etapie straty będą niewielkie.
Wykonaj `git reset --hard origin/master`. To spowoduje, że stracisz ostatnie zmiany jakie zrobiłaś na dysku, ale powinno trochę ułatwić sprawę. Po tej operacji powinnaś mieć w repo taki sam stan jak jest na githubie.

Nie wysyłaj plików przez upload file!

**Comment by Bialka** [comment]
Pokazało się to samo co na pierwszym screenie.

**Comment by Cosiek** [comment]
Więc usuń plik index.lock (polecenie `rm .git/index.lock` powinno załatwić sprawę), a potem `git reset --hard origin/master`

**Comment by Bialka** [comment]
Teraz jest już okej?
![efhef](https://user-images.githubusercontent.com/18377128/42537675-dd71bf56-8495-11e8-9fe8-27fbe2ca8d6c.png)

**Comment by Cosiek** [comment]
Chyba tak. Przenieś kod do cokolwiek.py, wywal nazwa.py, skomituj oba pliki i wypchnij.

**Comment by Bialka** [comment]
Dotarłam do tego miejsca i nie wiem co dalej. Wpisałam opis w pierwszą linijkę.
![opo](https://user-images.githubusercontent.com/18377128/42538287-d6680696-8497-11e8-9e37-1cd54fb0894c.png)

**Comment by Cosiek** [comment]
U - nie jest to jednoznaczne, ale chyba masz ustawionego VIM-a jako edytor tekstu.
Zmienimy.

Na razie wciśnij esc (napis insrt na dole powinien się zmienić na command lub coś podobnego), potem wpisz `:wq` i enter.

**Comment by Bialka** [comment]
![fad](https://user-images.githubusercontent.com/18377128/42539864-ade9f828-849c-11e8-9a67-827dd2d75351.png)

**Comment by Cosiek** [comment]
Spróbuj `:wq!`

**Comment by Bialka** [comment]
Chyba zadziałało.
![jdfoo](https://user-images.githubusercontent.com/18377128/42540423-a4227d90-849e-11e8-88bf-020dc4ef9a68.png)

**Comment by Bialka** [comment]
Gdy próbuję wypchnąć pokazuje się to:
![bez tytulu](https://user-images.githubusercontent.com/18377128/42540582-4b0c4460-849f-11e8-8c55-e21231ee7e0a.png)

**Comment by Cosiek** [comment]
Tylko `git push`, bez nazwy pliku.

**Comment by Cosiek** [comment]
> Aborting commit due to empty commit message

To jest komunikat o błędzie.
Spróbuj wygooglać jak zmienić domyślny edytor tekstu dla gita na windows. ustaw sobie chociażby notepad.txt - unikniemy w ten sposób kilku problemów.

**Comment by Bialka** [comment]
Ok, już wiem co zrobiłam źle.

**Comment by Bialka** [comment]
![fffd](https://user-images.githubusercontent.com/18377128/42560416-e19d22e4-84f6-11e8-9957-9e97e8edd8db.png)

**Comment by Cosiek** [comment]
Spróbuj wpisać w konsoli tylko `notepad` - jeśli otworzy Ci się notatnik, to wykonaj to - `config --global core.editor notepad` i spróbuj skomitować jeszcze raz. Jeśli nie zadziała, to spróbuj z `notepad.exe`.

**Comment by Bialka** [comment]
Udało się skomitować i wypchnąć. Teraz jak mam już ten kod w cokolwiek.py to mam usunąć nazwa.py?

**Comment by Cosiek** [comment]
Tak. Usuń nazwa.py i samo usunięcie też skomituj i wypchnij.

**Comment by Cosiek** [comment]
W opisie omita wpisuj co ten komit właściwie robi.

**Comment by Bialka** [comment]
Ale jak?

**Comment by Bialka** [comment]
Po prostu wejść do katalogu repozytorium usunąć plik po czym wejść w konsolę i go skomitować i wypchnąć?

**Comment by Cosiek** [comment]
> Po prostu wejść do katalogu repozytorium usunąć plik po czym wejść w konsolę i go skomitować i wypchnąć?

Tak. :smiley_cat:

**Comment by Bialka** [comment]
Okej, już.

**Comment by Cosiek** [comment]
:+1: Zamykam.
