### ISSUE TITLE
Opcja edycji

### ISSUE THREAD

**Issue by Cosiek** [Bialka/cokolwiek#30]
Do naszych dwóch akcji - przenoszenia i usuwania - chcemy dodać trzecią akcję - edycję.

Już o tym rozmawialiśmy, ale i tak napiszę.

Jeśli w pliku tekstowym cokolwiek.txt zastąpię w pierwszej kolumnie `-` literką `e`, to po ponownym odpaleniu programu, kiedy dojdzie on do obróbki katalogu z "e", zadzieją się wskazane rzeczy:
 - [x] program zbierze dane dotyczące plików w tym katalogu
 - [x] na podstawie tych danych utworzy kolejny plik tekstowy w formacie: ` - | ścieżka/do/pliku | numer ścieżki | tytuł | wykonawca | album | album artist | rok`
 - [x] otworzy ten drugi plik tekstowy w - powiedzmy notatniku
 - [x] zaczeka aż użytkownik zamknie notatnik
 - [x] wczyta dane z drugiego pliku tekstowego
 - [x] podejmie adekwatne akcje na wskazanych plikach - opis niżej
 - [x] po zakończeniu działań na plikach, przeniesie pliki z katalogu do katalogu docelowego
 - wróci do obsługi pliku cokolwiek.txt - czyli przejdzie do kolejnego katalogu

Akcje które będzie można wykonać na plikach:
 - `-` nic nie zmieniaj
 - `e` edytuj - przenieś dane z drugiego pliku tekstowego do tagów ID3 mp3
 - `u` usuwa plik z dysku

Jak widać, temat jest gruby. Porównywalnie gruby do wszystkiego co do tej pory było zrobione. Za to jest też w wielu kwestiach podobny do tego co już było zrobione, więc możesz się posiłkować kodem który już masz.

Wskazówki.
 - w terminalu ma windowsie powinnaś być w stanie zrobić coś takiego: `notepad plik.txt` (gdzie plik.txt to nazwa jakiegoś istniejącego pliku) i powinien otworzyć ci się ten plik w notatniku - do sprawdzenia.
 - jeśli powyższe zadziała, to można taki sam efekt otrzymać w pythonie korzystając z funkcji `subprocess.run` - jak dokładnie się jej używa, sprawdzisz sobie w internecie.
 - możesz sobie w tym opisie iszusa odhaczać co już jest zrobione.
 - otwórz pr-a jak tylko będziesz miała cokolwiek do pokazania - nie czekaj aż cała funkcjonalność będzie gotowa.

**Comment by Bialka** [comment]
Gotowe.
