### ISSUE TITLE
Inne nazwy plików.

### ISSUE THREAD

**Issue by Cosiek** [Bialka/cokolwiek#31]
W tej chwili, pliki mp3 są przenoszone do nowych właściwych katalogów, ale zachowują star nazwy.
Chcemy, żeby po przeniesieniu pliki miały nazwy w postaci `<numer ścieżki> <tytuł>.mp3`.

Czyli przykładowo: 
 - `01 The Blue Whale.mp3`
 - `02 Between the Devil and the Deep Blue Sea.mp3`
 - `03 Spinner Dolphin Superpod.mp3`
 - `04 The Deep.mp3`
 - `05 The Bait Ball.mp3`
 - [...]
 - `10 Red Hot Ants.mp3` 
 - `11 Etosha Lions.mp3`

Wskazówki:
 - trzeba specjalnie podejść do plików muzycznych - ale już podchodzisz do nich specjalnie
 - numer ścieżki i tytuł odczytasz mutagenem
 - dobrze byłoby jakoś sensownie obsłużyć sytuację, gdy pliki nie mają wypełnionych pól dotyczących numeru ścieżki lub tytułu

**Comment by Bialka** [comment]
Zamykam.
