### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by Cosiek** [Bialka/cokolwiek#35]
Skoro już uzyskaliśmy zamierzoną funkcjonalność, to możemy oznaczyć bieżącą wersję tagiem. W terminalu wpisz `git tag v0.1.0`, a potem `git push --tags`. Wtedy [tu](https://github.com/Bialka/cokolwiek/tags) powinien się pojawić twój tag.

Więc tak jak pisałem wcześniej - nasz program będzie miał dwie główne klasy `MusicDir` i `MusicFile`. Obie klasy będą jako argument przyjmowały ścieżki - odpowiednio do katalogu lub pliku. Klasa `MusicDir` będzie miała w `__init__` zadeklarowaną listę `self.music_files`. Elementami tej listy będą obiekty klasy `MusicFile` odpowiadające poszczególnym plikom tego katalogu.

Sekcja main w cokolwiek.py będzie teraz wyglądała z grubsza tak:
```python
if __name__ == "__main__":
    print("Zaczynam")
    file_path = 'cokolwiek.txt'
    current_dir = "do_zrobienia"
    destination_dir = "zrobione"

    if not os.path.exists(destination_dir):
        os.makedirs(destination_dir)

    music_files_dirs = collect_data_about_mp3(current_dir)
    if os.path.isfile(file_path):
        files_processing(music_files_dirs, file_path, destination_dir)
    else:
        record(music_files_dirs, file_path)
```
Gdzie `collect_data_about_mp3` będzie zwracała listę obiektów klasy `MusicDir`.

**Comment by Bialka** [comment]
Czyli zamiast klasy ```Dir``` mają być ```MusicDir``` i ```MusicFile```?

**Comment by Cosiek** [comment]
Tak. Chociaż precyzyjniej byłoby powiedzieć, że zamiast `Dir` ma być `MusicDir`, a oprócz tego ma być `MusicFile`.

**Comment by Bialka** [comment]
Co mam zrobić, żeby lokalnie na laptopie (w sensie na PyCharmie) wciągnąć branch? I żeby zauważył git zauważył, że na GitHubie jest już wciągnięty? W ```git help``` znalazłam ```git merge``` i ```git pull```, nie jestem pewna czego użyć.

**Comment by Cosiek** [comment]
Przejdź na mastera i zrób git pull.

**Comment by Bialka** [comment]
Okej, udało mi się.
