### ISSUE TITLE
Wydzielenie wczytywania danych z plików

### ISSUE THREAD

**Issue by Cosiek** [Bialka/cokolwiek#37]
Więc w klasie `MusicFile` mamy metodę `read_tags`. Chcę, żeby ta metoda pozostała w klasie, ale jej implementacja powinna wyglądać tak:

```
    def read_tags(self):
        for key, val in get_file_tags(self.file_path).items():
            setattr(self, key, val)
```

gdzie `get_file_tags` będzie funkcją zapisaną w oddzielnym pliku. Będzie przyjmować nazwę pliku i zwracać słownik w takiej postaci:
```
{
    "tracknumber": None,
    "title": None,
    "artist": None,
    "album_artist": None,
    "album_title": None,
    "year": None,
}
```
Każdy z wymienionych tu kluczy powinien być w słowniku, nawet jeśli nie da się ustalić właściwej wartości - wtedy powinno być `None`.

Wyznaczenie poszczególnych wartości słownika powinno być realizowane przez wyspecjalizowane pod tym względem funkcje, ale dobrze jest nie powtarzać niepotrzebnie tego samego kodu.

**Comment by Bialka** [comment]
Zrobione. Zamykam.
