### ISSUE TITLE
Małe porządki.

### ISSUE THREAD

**Issue by Cosiek** [Bialka/cokolwiek#4]
Kilka rzeczy które w tej chwili nie mają specjalnie znaczenia, ale potem o nich zapomnimy, a dobrze sobie wyrabiać właściwe nawyki.

Na górze `cokolwiek.py` dodaj taki kod:
```
#!/usr/bin/env python
# encoding: utf-8
```

"Witaj świecie" zmień na jakiś inny komunikat (może "Zaczynam" ?).

Wstaw pętlę for którą już masz, za warunek, w taki sposób:
```
if __name__ == "__main__":
    for x in os.walk("do_zrobienia"):
        print x
```
Zwróć uwagę na wcięcia. W Pythonie wcięcia są bardzo ważne. Kod wcięty po if wykona się tylko jeśli warunek będzie spełniony. Kod wcięty po for wykona się po jednym razie dla każdego elementu x który zwróci funkcja `os.walk`.

Każdą z tych trzech operacji skomituj oddzielnie, z właściwym opisem (czyli wykonujesz coś, sprawdzasz czy program wciąż działa, jeśli tak, to komitujesz i przechodzisz do robienia kolejnej zmiany w kodzie). Na koniec wypchnij zmiany do githuba.

**Comment by Bialka** [comment]
O co chodzi z tym ostrzeżeniem? Pokazało się po skomitowaniu pierwszych zmian (ten kod na górze).
![dkvmkd](https://user-images.githubusercontent.com/18377128/42563923-baf7c3c0-84ff-11e8-9edd-8c72f1994a25.png)

**Comment by Cosiek** [comment]
Nie podoba mu się, że użyłaś polskiego znaku (ó) w opisie komita.
Raczej nie musisz się tym przejmować.

**Comment by Bialka** [comment]
Ok.

**Comment by Bialka** [comment]
Gdy chcę  skomitować ostatnie zmiany pokazuje mi się to:
![poo](https://user-images.githubusercontent.com/18377128/42565630-46df7032-8504-11e8-9a3c-4add52d0f3df.png)

**Comment by Cosiek** [comment]
> Your branch is ahead of 'origin/master' by 2 commits.

To znaczy, że masz u siebie dwa kommity, których jeszcze nie wypchnęłaś do githuba. Czyli wszystko tak jak miało być.

> Untracked files

Tu wyświetla Ci listę plików które są w repozytorium (katalogu), ale git ich nie obserwuje. Widzę, że masz tu jakiś plik readme.md.txt - możesz go zwyczajnie usunąć - to jakiś śmieć.

> notging added to commit

To znaczy, że git nie widzi zmian w pliku `cokolwiek.py`. Podejrzewam, że skomitowałaś je już w poprzednim komicie. Wypchnij wszystko na githuba (`git push`).

**Comment by Cosiek** [comment]
Dwie dodatkowe notki:
 - Wygooglaj sobie, jak w konsoli powershell kopiować tekst - żebyś nie musiała robić print-screenów.
 - Wpisz w konsolę `git gui` i daj znać, czy coś się odpaliło.
 - Wpisz w konsolę `gitk` i daj znać jaki był wynik.

**Comment by Bialka** [comment]
W cokolwiek.py już jest wszystko.

**Comment by Bialka** [comment]
Po wpisaniu "git gui" pojawiło się okienko Git Gui, a po wpisaniu "gitk" wyskoczyło okienko, gdzie pisało, że nie może znaleźć repozytorium gita.

**Comment by Cosiek** [comment]
> gdzie pisało

Było napisane :imp: 

Wpisałaś to w konsolę kiedy byłaś w katalogu projektu? Jeśli nie to spróbuj jeszcze raz.

**Comment by Cosiek** [comment]
Knm. Miałaś wprowadzić zmiany **i sprawdzić czy program wciąż działa**.

**Comment by Bialka** [comment]
Teraz jak wpisałam "gitk" to pojawiło się takie okienko:
![bez tytulu](https://user-images.githubusercontent.com/18377128/42628475-8c329462-85d0-11e8-8f6a-e9a1c7daba32.png)

**Comment by Bialka** [comment]
Po ostatnich zmianach zapomniałam.

**Comment by Cosiek** [comment]
Więc w gitk możesz podejrzeć historię swoich komitów i zobaczyć czy stan twojego repozytorium (etykietka "master") zgadza się ze stanem na githubie (etykietka "remotes/origin/master").

`git gui` może będzie dla Ciebie pomocny przy komitowaniu. Masz tam dwie listy po lewej stronie.
"Unstaged Changes" to zmiany które wymagają zestagowania. Jeśli wybierzesz plik z tej lisy i wciśniesz "Ctrl T", to plik się przeniesie na tę niższą listę (to jest odpowiednik wykonania `git add plik.cos` w konsoli).
Jak już wszystkie pliki które chcesz skomitować **razem** znajdą się na niższej liście, Wystarczy wpisać nazwę komita w pole "Commit Message" i wcisnąć commit (odpowiednik `git commit` w konsoli).
Masz też guzik "Push" - wypycha kod na githuba.
Resztę opcji pewnie rozkminisz sama.

**Comment by Bialka** [comment]
Ok.

**Comment by Cosiek** [comment]
Teraz co do kodu. Jak odpalisz program, będziesz miała coś takiego:
```
python cokolwiek.py 
Zaczynam
Traceback (most recent call last):
  File "cokolwiek.py", line 7, in <module>
    if _name_ == "_main_":
NameError: name '_name_' is not defined
```
To co widisz po słówku "Tracebck" to ...traceback. Komunikat mówiący na czym polegał błąd. Ważne, żebyś zwracała na nie uwagę i nauczyła się ich czytać. Najważniejsza jest ostatnia linijka - mówi na czym polega błąd. Wcześniejsze mówią w którym miejscu w kodzie błąd wystąpił - nazwa pliku i linijka.

Tutaj popełniłaś błąd który pewnie będzie Ci się zdarzał najczęściej - literówka.
Powinno być:
`__name__ == "__main__"` a nie 
`_name_ == "_main_"`.

**Comment by Bialka** [comment]
Poprawiłam, teraz jest dobrze. I działa.

**Comment by Cosiek** [comment]
W opisie komita pisz co on robi.
Ten ostatni mógł się nazywać "Poprawiam literówkę (_name_ > __name__)". Ogólna zasada jest taka, że opis komita zaczyna się od czasownika - choć nie ma co się tego zbyt kurczowo trzymać.

Dobra - zamykam i piszę kolejny issue.
