### ISSUE TITLE
Zagnieżdrzona pętla - wypisać pliki

### ISSUE THREAD

**Issue by Cosiek** [Bialka/cokolwiek#5]
Jak może zauważyłaś zmienna `x` składa się z trzech wartości.
 - ścieżki względnej do katalogu (jeśli chcesz to wyprintować, zrób `print(x[0])` - to jest odwołanie do ierwszego elementu krotki (tuple) x)
 - listy podkatalogów (`print(x[1])`)
 - listy plików w katalogu (`print(x[2])`)

Chcę, żeby program printował ścieżkę katalogu, a niżej, kolejno nazwy plików które się w nim znajdują.
Ma to wyglądać mniej więcej tak:
```
do_zrobienia/Taal
    01. Ishq Bina.mp3
    02.Taal Se Taal (Western).mp3
do_zrobienia/Sirens
    01 Circe's Island.mp3
    02 Persephone River Of Tears.mp3
```

Żeby to zrobić, musisz przeiterować po liście plików - czyli po trzecim elemencie x - `x[2]`. To znaczy, że musisz napisać pętlę for, wewnątrz tej pętli którą już masz. Twoja druga pętla for będzie miała analogiczną budowę do tej którą już masz, sle zamiast `os.walk("do_zrobienia")`, wstawisz `x[2]`.

Spróbuj na razie sama i wklej mi kod tutaj jak coś będziesz miała.

**Comment by Cosiek** [comment]
Żeby wyprintować coś z wcięciem na początku, możesz zrobić tak:
`print("\t", zmienna)`

**Comment by Bialka** [comment]
Ta pętla ma być pod czy nad "print (x)"?

**Comment by Cosiek** [comment]
Ma nie być `print(x)`. Ma być `print(nazwa_pliku)`.

Dokładniej:
```python
for nazwa_pliku in x[2]:
    print(nazwa_pliku)
```

**Comment by Bialka** [comment]
print ("Zaczynam")
if __name__ == "__main__":
    for x in os.walk("do_zrobienia"):
        for nazwa_pliku in x[2]:
            print("\t", nazwa_pliku)
Tak?

**Comment by Bialka** [comment]
Jest z wcięciami.

**Comment by Cosiek** [comment]
Dokładnie tak. :+1: Skomitować i wypchnąć.

P.S. Jak chcesz wkleić blok kodu na githubie, to wpisz 3 razy \`, potem wklej kod i zamknij znowu 3 razy \` (klawisz na lewo od jedynki, pod esc)

**Comment by Bialka** [comment]
Już.

**Comment by Cosiek** [comment]
Źle wcięcia.

**Comment by Bialka** [comment]
A jak powinny być?

**Comment by Cosiek** [comment]
```
print ("Zaczynam")
if __name__ == "__main__":
    for x in os.walk("do_zrobienia"):
        for nazwa_pliku in x[2]:
            print("\t", nazwa_pliku)
```

W obecnej postaci program nie działa:
```
python cokolwiek.py 
  File "cokolwiek.py", line 9
    for nazwa_pliku in x[2]:
      ^
IndentationError: expected an indented block
```

**Comment by Bialka** [comment]
Już poprawiłam.

**Comment by Cosiek** [comment]
Zgubiłaś jeszcze wyprintowanie nazwy katalogu, ale niech tak będzie. Doda się w kolejnym zadaniu.

Zamykam.
