### ISSUE TITLE
Powrót klas

### ISSUE THREAD

**Issue by Cosiek** [Bialka/cokolwiek#56]
Co prawda następne na liście jest dostosowanie poziomu głośności, ale sam jeszcze nie do końca wiem jak to zrobić, więc na razie tylko się pod to przygotujemy.

Do tej pory `processing_to_verification` to było wywołanie kilku niezależnych funkcji, które przyjmowały ten sam parametr - `processing_dir_path`. Kolejne trzy punkty jakie mamy do zrobienia - dostosować poziom głośności, znormalizować tagi oraz pozbyć się zbędnych tagów będą wymagały działań na tagach (tak - normalizacja głośności też). Dlatego chyba czas zacząć używać obiektów (`class`).

Więc teraz chcemy funkcję, która zwróci listę obiektów klasy MusicDir z których każdy będzie miał listę obiektów MusicFile - tak samo jak wcześniej. Potem podopisujemy do nich co trzeba.

**Comment by Bialka** [comment]
To masz trochę czasu, żeby nad tym pomyśleć, bo nie wzięłam ze sobą laptopa na wakacje i dopiero w następny poniedziałek się za to wezmę.

**Comment by Bialka** [comment]
Nie jestem pewna, czy dobrze zrozumiałam - chodzi o to, żeby funkcja zwróciła listę z plikami, które znajdzie MusicDir, i żeby dla każdego pliku była lista obiektów MusicFile, czyli album_artist itd. ? Czy ta funkcja ma się znajdować w `ogarniacz_mp3.py`?

**Comment by Cosiek** [comment]
Chcemy funkcję, która zwróci listę obiektów klasy MusicDir (po jednym dla każdego katalogu i podkatalogu który zawiera pliki muzyczne) z których każdy będzie miał listę obiektów MusicFile (po jednym dla każdego pliku muzycznego w danym katalogu/podkatalogu).

**Comment by Bialka** [comment]
Zamykam.
