### ISSUE TITLE
Tylko jeśli mp3

### ISSUE THREAD

**Issue by Cosiek** [Bialka/cokolwiek#6]
Rozwinięcie poprzedniego zadania.

Program ma wyświetlać ścieżki katalogów i pliki w tych katalogach, tak samo jak do taj pory, ale dochodzą dodatkowe warunki. 
 - wyświetlaj tylko nazwy plików, które mają rozszerzenie `mp3`
 - wyświetlaj tylko te katalogi, w których jest przynajmniej jeden plik `mp3`

Żeby sprawdzić rozszerzenie pliku, możesz posłużyć się funkcją `endswith()`. Coś takiego:
```
if nazwa_pliku.endswith(".mp3"):
    print(nazwa_pliku)
```

**Comment by Bialka** [comment]
Tak?
```if __name__ == "__main__":
    for x in os.walk("do_zrobienia"):
        for nazwa_pliku in x[2]:
            if nazwa_pliku.endswith(".mp3"):
                print("\t", nazwa_pliku)

**Comment by Cosiek** [comment]
Tak, przy czym to Ci rozwiąże tylko pierwszą część problemu:

> wyświetlaj tylko nazwy plików, które mają rozszerzenie mp3

Do zrobienia pozostało jeszcze:

> wyświetlaj tylko te katalogi, w których jest przynajmniej jeden plik mp3

Przypominam, że to miało wyglądać tak:
```
śceżka/do/katalogu
    nazwa_pliku1.mp3
    nazwa_pliku2.mp3
    nazwa_pliku3.mp3
śceżka/do/innego/katalogu
    inna_nazwa_pliku1.mp3
    inna_nazwa_pliku2.mp3
    inna_nazwa_pliku3.mp3
```

Możesz skomitować, to co masz, a printowanie katalogu zrobić skomitować oddzielnie.

**Comment by Bialka** [comment]
Już zrobiłam i wypchnęłam. Wszystko działa.

**Comment by Cosiek** [comment]
Czytanie ze zrozumieniem się kłania. Masz wyprintować **ścieżkę do katalogu** (`x[0]`), ale **tylko** jeśli są w nim pliki mp3.

**Comment by Bialka** [comment]
Mam coś takiego:
```for x in os.walk("do_zrobienia"):
        for nazwa_pliku in x[2]:
            if nazwa_pliku.endswith(".mp3"):
                print ("\t", x[0])
                print("\t", nazwa_pliku)

**Comment by Bialka** [comment]
I teoretycznie działa, bo printuje ścieżkę katalogu tylko jeśli są w nim pliki mp3, ale przy każdym utworze od nowa pisze katalog, i nie wiem jak to poprawić.

**Comment by Cosiek** [comment]
`print ("\t", x[0])` - Ścieżka do katalogu ma się printować bez wcięcia.

Kombinuj.

Możesz np. powtórzyć pętlę, po to żeby sprawdzić katalog,a dopiero potem printować pliki w drugiej pętli.

Możesz utworzyć zmienną pomocniczą, do której będziesz dodawała nazwy katalogów, a potem w pętli `pomoc = "\t" + nazwa_pliku`, a po pętli sprawdzała, czy należy wyprintować zmienną pomocniczą.

Możesz wewnątrz warunku `if nazwa_pliku.endswith(".mp3"):` sprawdzić, czy to pierwszy plik który spełnia warunek (też będzie potrzebna zmienna pomocnicza), i tylko jeśli tak, to printować katalog.

**Comment by Bialka** [comment]
A jak zrobić tą zmienną pomocniczą?

**Comment by Cosiek** [comment]
Na przykład tak:

```
if __name__ == "__main__":
    for x in os.walk("do_zrobienia"):
        juz_wyprintowany = False
        for nazwa_pliku in x[2]:
            if nazwa_pliku.endswith(".mp3"):
                if not juz_wyprintowany:
                    print ("\t", x[0])
                    juz_wyprintowany = False
                print("\t", nazwa_pliku)
```

Tak żeby nie było za łatwo, wprowadziłem tu jeden błąd (jeden celowo, za resztę nie ręczę). Dlatego masz to przeczytać, zrozumieć i poprawić - a nie tylko przekopiować.

**Comment by Cosiek** [comment]
U - widzę jeszcze jeden błąd. :smiling_imp:

**Comment by Bialka** [comment]
Pierwszy błąd - powinno być 

```print (x[0])```

zamiast

```print ("\t", x[0])```

Drugi - po tym wyprintowaniu powinno być

```juz_wyprintowany = True```

a nie

```juz_wyprintowany = False```

**Comment by Bialka** [comment]
A całość wygląda tak:

```if __name__ == "__main__":
    for x in os.walk("do_zrobienia"):
        juz_wyprintowany = False
        for nazwa_pliku in x[2]:
            if nazwa_pliku.endswith(".mp3"):
                if not juz_wyprintowany:
                    print (x[0])
                    juz_wyprintowany = True
                print("\t", nazwa_pliku)```

**Comment by Cosiek** [comment]
Super. :ok_hand: 
Skomitować i wypchnąć.

**Comment by Cosiek** [comment]
@Bialka - Skomitować i wypchnąć zanim pójdziesz dalej.

**Comment by Bialka** [comment]
Zapomniałam. Już to robię.

**Comment by Bialka** [comment]
Już wypchnięte.

**Comment by Cosiek** [comment]
:ok: Zamykam issue.
