### ISSUE TITLE
Koniec z printowaniem - zbieramy dane do słownika.

### ISSUE THREAD

**Issue by Cosiek** [Bialka/cokolwiek#7]
Tak jak w tytule. Chcę, żeby program tworzył słownik, który będzie trzymał dane o naszych plikach.

Słownik jest jedną z podstawowych struktur danych w Pythonie. Tu mała próbka co to robi:
```python
slownik = {}  # deklaracja zmiennej o nazwie "słownik" i  wartości będącej pustym słownikiem
slownik["jeden"] = 1  # zapisanie wartości w słowniku. "jeden" jest kluczem, a 1 jest wartością
slownik[1] = "jeden"  # tutaj odwrotnie - 1 jest kluczem, a "jeden" wartością
                                 # kluczem może być każdy obiekt który jest hashowalny
                                 # wartością może być praktycznie wszystko
print(slownik)   # podgląd - da coś takiego {1: "jeden", "jeden": 1}
print(slownik["jeden"])  # wyprintuje 1 - pobranie wartości ze słownika po kluczu
slownik["L"] = [1,2,3]  # do klucza "L" przyisuje listę trzyelementową
```

Twoje zadanie, to przerobić program tak, żeby utworzył pusty słownik, a następnie wypełnił go, tak że ścieżka do katalogu (`x[0]`) będzie kluczem, a wartością będzie lista plików z rozszerzeniem "mp3".

Listy pisze się tak:
```
nowa = []  # deklaracja nowej pustej listy
nowa.append("jeden")  # dopisanie "jeden" do końca losty
nowa.append("dwa")  # dopisanie "dwa" do końca losty
print(nowa[0])  # wyprintuje pierwszy element na liście - "jeden"
print(nowa[1])  # wyprintuje drugi element na liście - "dwa"
# listy są indeksowane od 0, dlatego pierwszy element ma indeks 0, drugi 1, trzeci 2 itd.
```

**Comment by Cosiek** [comment]
To jeszcze małe uzupełnienie. Nie chcemy więcej printować ani ścieżek do katalogów, ani plików.
Za to po utworzeniu słownika, chcę żeby wyprintowało się coś takiego: "Znaleziono 12 plików w 4 katalogach.".

Żeby dostać taki string (tekst - ciąg znaków), można zrobić tak:
`"Znaleziono {} plików w {} katalogach.".format(licznik_plikow, licznik_katalogow)`

**Comment by Bialka** [comment]
A mam utworzyć nowy plik, czy robić to w cokolwiek.py ?

**Comment by Bialka** [comment]
Już nie ważne.

**Comment by Bialka** [comment]
To ma być jakoś tak?

```
slownik = {}
nowa = []

slownik[(x[0])] = nowa
nowa.append(for x in os.walk("do_zrobienia"):
                juz_wyprintowany = False
                for nazwa_pliku in x[2]:
                    if nazwa_pliku.endswith(".mp3"):
                        if not juz_wyprintowany:
                            print (x[0])
                            juz_wyprintowany = True
                        print("\t", nazwa_pliku))
print ("Zaczynam")
print(slownik[(x[0])])
print ("Znaleziono {} plików w {} katalogach." .format(licznik_plikow, licznik_katalogow))

**Comment by Cosiek** [comment]
Pierwsza myśl - spróbuj to uruchomić i zobacz co się stanie.

Druga myśl - o ile część elementów się zgadza, to logiki `nowa.append(for x in os.walk("do_zrobienia"):` zupełnie nie widzę. A to zawsze będzie logiczne, nawet jeśli nie zawsze oczywiste.

Wskazówka a nie odpowiedź:
```
print ("Zaczynam")
if __name__ == "__main__":
    slownik = {}
    licznik_plikow = 0
    licznik_katalogow = 0
    for x in os.walk("do_zrobienia"):
        nowa_lista = []
        for nazwa_pliku in x[2]:
            if nazwa_pliku.endswith(".mp3"):
                nowa_lista.append(nazwa_pliku)
    print("To co należy wyprintować")
```

Podpowiedź odnośnie liczników. Jeśli chcesz zwiększyć wartość zmiennej, to możesz zrobić to tak: `licznik = licznik + 1`. Ponieważ jednak w programowaniu robi się takie rzeczy bardzo często, to w skrócie możesz to zrobić tak: `licznik += 1`.

Możesz sprawdzić, czy lista zawiera jakieś elementy pisząc po prostu `if lista:`. Warunek będzie spełniony, jeśli coś jest na liście, nie będzie, jeśli jest pusta. Zadziała podobnie ze słownikiem - pusty słownik zachowa się jak `False`, a zawierający jakieś klucze zachowa się jak `True`.

Możesz też sprawdzać czy klucz jest w słowniku w taki sposób: `if klucz in slownik:`.

**Comment by Cosiek** [comment]
Hej.
Zamierzasz wrócić do tego?

**Comment by Bialka** [comment]
Powróciłam.

**Comment by Bialka** [comment]
Nie odzywałam się, bo miałam wyjazdy i obozy.

**Comment by Cosiek** [comment]
Fajnie, że jesteś.
Trochę słabo, że ja pojutrze wyjeżdżam.

**Comment by Bialka** [comment]
Mam tyle

```print ("Zaczynam")
if __name__ == "__main__":
    slownik = {}
    licznik_plikow = 0
    licznik_katalogow = 0
    for x in os.walk("do_zrobienia"):
        nowa_lista = []
        for nazwa_pliku in x[2]:
            if nazwa_pliku.endswith(".mp3"):
                nowa_lista.append(nazwa_pliku)
    slownik[(x[0])] = nowa_lista
    print(slownik["(x[0])"])
    print("Znaleziono {} plików w {} katalogach.".format(licznik_plikow, licznik_katalogow)) ```


i wyskakuje mi taki błąd jak próbuję odpalić


``` Zaczynam
Traceback (most recent call last):
  File "cokolwiek.py", line 17, in <module>
    print(slownik["x[0]"])
KeyError: 'x[0]'```


i nie wiem jak to naprawić.

**Comment by Bialka** [comment]
Poprawiłam i działa. Komituję i wypycham.

**Comment by Bialka** [comment]
Już.

**Comment by Cosiek** [comment]
O ile faktycznie obecna wersja pewnie działa poprawnie, w kwestii zbierania nazw plików do słownika, to jednak nie do końca jest dobrze.

Zapisanie listy w słowniku (`slownik[(x[0])] = nowa_lista`), powinno być wykonane raz, dla każdego katalogu w którym znajdziesz plik mp3, a nie za każdym razem kiedy znajdziesz plik mp3. Zwróć uwagę na poziomie której pętli to robisz.

Zauważyłem też, że w obecnej wersji podbijasz licznik katalogów, za każdym razem kiedy znajdziesz plik mp3. To błąd - one nie będą równe z definicji. Linijkę `licznik_katalogow += 1` musisz przenieść w inne miejsce - zastanów się jakie.

**Comment by Bialka** [comment]
A teraz?

```print ("Zaczynam")
if __name__ == "__main__":
    slownik = {}
    licznik_plikow = 0
    licznik_katalogow = 0
    for x in os.walk("do_zrobienia"):
        nowa_lista = []
        licznik_katalogow += 1
        for nazwa_pliku in x[2]:
            if nazwa_pliku.endswith(".mp3"):
                nowa_lista.append(nazwa_pliku)
                licznik_plikow += 1
        if nowa_lista:
            slownik[(x[0])] = nowa_lista
    print(slownik)
    print("Znaleziono {} plików w {} katalogach.".format(licznik_plikow, licznik_katalogow))

**Comment by Cosiek** [comment]
- przeniesienie `slownik[(x[0])] = nowa_lista` - :+1: 
 - przeniesienie `licznik_katalogow += 1` - :-1: - teraz zliczasz wszystkie katalogi, nie tylko te które zawierają pliki mp3

Jesteś jedną linijkę od dobrego rozwiązania. :smile:

**Comment by Bialka** [comment]
A teraz?
```
print ("Zaczynam")
if __name__ == "__main__":
    slownik = {}
    licznik_plikow = 0
    licznik_katalogow = 0
    for x in os.walk("do_zrobienia"):
        nowa_lista = []
        for nazwa_pliku in x[2]:
            licznik_katalogow += 1
            if nazwa_pliku.endswith(".mp3"):
                nowa_lista.append(nazwa_pliku)
                licznik_plikow += 1
        if nowa_lista:
            slownik[(x[0])] = nowa_lista
    print(slownik)
    print("Znaleziono {} plików w {} katalogach.".format(licznik_plikow, licznik_katalogow))

**Comment by Cosiek** [comment]
Jeszcze gorzej. Teraz `licznik_katalogow` zlicza wszystkie pliki - niezależnie od typu.
Zastanów się, która część tego kodu uruchamia się tylko raz dla katalogu w którym są mp3?

Może warto też, żebyś sobie przygotowała pliki i katalogi w do_zrobienia, tak żebyś mogła sama zweryfikować wyniki.

**Comment by Bialka** [comment]
```
print ("Zaczynam")
if __name__ == "__main__":
    slownik = {}
    licznik_plikow = 0
    licznik_katalogow = 0
    for x in os.walk("do_zrobienia"):
        licznik_katalogow += 1
        nowa_lista = []
        for nazwa_pliku in x[2]:
            if nazwa_pliku.endswith(".mp3"):
                nowa_lista.append(nazwa_pliku)
                licznik_plikow += 1
        if nowa_lista:
            slownik[(x[0])] = nowa_lista
    print(slownik)
    print("Znaleziono {} plików w {} katalogach.".format(licznik_plikow, licznik_katalogow))            
```
?

**Comment by Cosiek** [comment]
Wróciłaś do poprzedniej wersji.
Podpowiedź / odpowiedź:
```
if nowa_lista:
    slownik[(x[0])] = nowa_lista
    licznik_katalogow += 1
```

**Comment by Bialka** [comment]
Okej. Skomitować i wypchnąć?

**Comment by Cosiek** [comment]
Tak.

**Comment by Bialka** [comment]
Już.

**Comment by Cosiek** [comment]
Super. Zamykam i przechodzimy do kolejnego issue.
