### ISSUE TITLE
Poznajemy funkcje.

### ISSUE THREAD

**Issue by Cosiek** [Bialka/cokolwiek#8]
Czas napisać pierwszą funkcję. Po co? Bo dzięki funkcjom będziesz mogła lepiej organizować kod i będziesz mogła wielokrotnie wykorzystywać ten sam kod, bez przepisywania go.

Więc nową funkcję się deklaruje np. w taki sposób:
```python
def nazwa_funkcji(argument1, argument2):
    # jakikolwiek kod
    wynik_obliczen = argument1 + argument2
    return wynik_obliczen * 2  # zwrócenie wartości
```
A potem można jej użyć np. tak:
```python
wynik_obliczen = nazwa_funkcji(argument1, argument2)
```

Przykład bardziej praktyczny:
```python
def kwadrat_sumy(arg1, arg2):
    return (arg1 + arg2) ** 2

print kwadrat_sumy(2, 3)  # wyprintuje 25
```

Twoje zadanie, to napisać funkcję o nazwie "zbierz_dane_o_mp3", która jako argument będzie przyjmowała nazwę katalogu, a zwracać będzie słownik, taki jak ten który teraz printujesz.

Czyli część `__main__` twojego pliku powinna teraz wyglądać tak:
```python
print ("Zaczynam")
if __name__ == "__main__":
    slownik = zbierz_dane_o_mp3("do_zrobienia")
    print(slownik)
```

Linijkę `print("Znaleziono {} plików w {} katalogach.".format(licznik_plikow, licznik_katalogow))` możesz albo wyrzucić, albo przenieść do wnętrza funkcji.

Nowa wersja powinna printować dokładnie taki sam słownik, jak obecna.

Dobrze wiedzieć:
 - funkcja nie musi przyjmować argumentów,
 - funkcja nie musi mieć klauzuli `return` - wtedy zwraca wartość `None`.

To jest zupełnie dobra funkcja:
```python
def powiedz_czesc():
    print "Cześć"
```

**Comment by Bialka** [comment]
Witam ponownie. Udało mi się nareszcie znaleźć czas na to. Teraz zabieram się za te funkcje ^. 
W trakcie pobiera mi się Linux. Jak będzie najłatwiej przerzucić pliki z jednego systemu na drugi? Przez pendriva? I jak przy włączaniu komputera wybrać który system ma się włączyć? Bo tak pewnie trzeba będzie zrobić?

**Comment by Bialka** [comment]
Na razie mam tyle : 
```def zbierz_dane_o_mp3(arg1):
    wynik_obliczen = arg1
    return wynik_obliczen * 1

print ("Zaczynam")
if __name__ == "__main__":
    slownik = zbierz_dane_o_mp3("do_zrobienia")
    print(slownik)    
```

Idę w dobrą stronę?

**Comment by Cosiek** [comment]
Linux powinien widzieć partycje (dyski) windowsowe, więc nie będziesz musiała niczego przerzucać. Jeśli instalacja pójdzie poprawnie, to zainstaluje Ci się też GRUB - po uruchomieniu komputera będzie pojawiać się ekran na którym będziesz mogła wybrać który system ma się uruchomić.

Chyba nie wkleiłaś wszystkiego, ale tak na oko, to nie idziesz w dobrą stronę. Nie widzę deklaracji funkcji - `def zbierz_dane_o_mp3(dir_name):`, a to co jest, to jakiś mały fragment przeklejony z przykładu który podałem. Twoja funkcja ma robić to co do tej pory było robione w części `if __name__ == "__main__":` - musisz przenieść kod stamtąd do wnętrza funkcji.

**Comment by Bialka** [comment]
Okej.

**Comment by Bialka** [comment]
```
def zbierz_dane_o_mp3(do_zrobienia):
    wynik_obliczen = do_zrobienia
    return wynik_obliczen * 1

print ("Zaczynam")
if __name__ == "__main__":
    slownik = {}
    licznik_plikow = 0
    licznik_katalogow = 0
    for x in os.walk("do_zrobienia"):
        nowa_lista = []
        for nazwa_pliku in x[2]:
            if nazwa_pliku.endswith(".mp3"):
                nowa_lista.append(nazwa_pliku)
                licznik_plikow += 1
        if nowa_lista:
            slownik = nowa_lista
            licznik_katalogow += 1 
    print(slownik)            
```
Mam tyle i wszystko byłoby ok, gdyby nie to, że nie printuje wszystkiego.

**Comment by Cosiek** [comment]
Mam wrażenie, że robisz to trochę na chybił trafił, a ja nie mam pomysłu jak Ci to lepiej wytłumaczyć. 
Masz jeszcze raz **uważnie** przeczytać [opis zadania](https://github.com/Bialka/cokolwiek/issues/8#issue-355931498) i spróbować go zrozumieć. Jeśli czegoś nie rozumiesz, to zapytaj, ale nie pisz kolejnej wersji, dopóki nie zrozumiesz.

**Comment by Bialka** [comment]
Możesz mi jeszcze raz wyjaśnić tak jak wtedy, gdy byłeś w Płońsku?

**Comment by Cosiek** [comment]
Ech...
```python
def zbierz_dane_o_mp3(katalog):
    slownik = {}
    licznik_plikow = 0
    licznik_katalogow = 0
    for x in os.walk(katalog):
        nowa_lista = []
        for nazwa_pliku in x[2]:
            if nazwa_pliku.endswith(".mp3"):
                nowa_lista.append(nazwa_pliku)
                licznik_plikow += 1
        if nowa_lista:
            slownik[(x[0])] = nowa_lista
            licznik_katalogow += 1
    print("Znaleziono {} plików w {} katalogach.".format(licznik_plikow, licznik_katalogow))
    return slownik


print ("Zaczynam")
if __name__ == "__main__":
    slownik = zbierz_dane_o_mp3("do_zrobienia")
    print(slownik)
```

To jest rozwiązanie całego zadania. Masz sprawdzić czy działa, przeanalizować i zrozumieć (zwróć szczególnie uwagę jak się przekazuje argument do funkcji, jak się zwraca wynik funkcji).
Potem daj mi znać, to zrobię kolejne zadanie.

**Comment by Bialka** [comment]
```
File "cokolwiek.py", line 20
    return slownik * 1
         ^
SyntaxError: invalid syntax
```
Pokazuje taki błąd.

**Comment by Bialka** [comment]
Już nie ważne.

**Comment by Bialka** [comment]
O co chodzi z tym przekazaniem argumentu do funkcji?

**Comment by Cosiek** [comment]
Wróćmy do przykładu z początku tego issue:
```python
# deklaracja funkcji
def kwadrat_sumy(arg1, arg2):
    return (arg1 + arg2) ** 2

# wywołanie funkcji
print kwadrat_sumy(2, 3)  # wyprintuje 25
```
Mamy tutaj deklarację funkcji, która przyjmuje dwa argumenty `arg1` i `arg2`. Kiedy wywołujesz tę funkcję - `kwadrat_sumy(2, 3)` - komputer wykonuje po kolei instrukcje które są zawarte w deklaracji (tutaj jest to tylko `return (arg1 + arg2) ** 2`), przy czym jako wartość `arg1` widzi `2`, a jako wartość `arg2` widzi `3`.
Czy rozumiesz co próbuję przekazać?

**Comment by Bialka** [comment]
Tak. Tylko czemu wyprintuje 25?

**Comment by Bialka** [comment]
I czemu tutaj
```
def zbierz_dane_o_mp3(katalog):
```
i tutaj
```
for x in os.walk(katalog):
```
jest w nawiasie "katalog"? Wydawało mi się, że trzeba wpisać nazwę katalogu, czyli w tym wypadku "do_zrobienia".

**Comment by Bialka** [comment]
Czy te podwójne gwiazdki znaczą, że pomnoży 3 razy?

**Comment by Bialka** [comment]
Tylko, że (2+3)*3 wciąż nie daje 25.

**Comment by Cosiek** [comment]
> Czy te podwójne gwiazdki znaczą, że pomnoży 3 razy?

**Nie!** Skąd w ogóle te 3 wytrzasnęłaś? Przecież było:
```
def kwadrat_sumy(arg1, arg2):
    return (arg1 + arg2) ** 2
```

 - `x * y` znaczy x razy y
 - `x ** y` znaczy x do potęgi y

Swoją drogą - funkcja nie bez powodu się  nazywa **kwadrat sumy**.

**Comment by Cosiek** [comment]
> I czemu tutaj [...] jest w nawiasie "katalog"?

Właśnie na to chciałem, żebyś zwróciła uwagę.
Fragment komentarza sprzed kilku godzin:

> ...przy czym jako wartość arg1 widzi 2, a jako wartość arg2 widzi 3.

Tak tutaj analogicznie. Po wywołaniu funkcji `zbierz_dane_o_mp3("do_zrobienia")` wykona się kod który jest wewnątrz tej funkcji, ale do zadeklarowanej nazwy argumentu "katalog", zostanie przypisana wartość podana przy wywołaniu funkcji - czyli "do_zrobienia".

Przepuśćmy, że miałabyś pliki mp3 w trzech różnych katalogach. Zamiast pisać cały kod trzy razy, zmieniając tylko nazwę katalogu, możesz to zrobić przy pomocy trzech wywołań funkcji, podając inne parametry:
```python
zbierz_dane_o_mp3("do_zrobienia")
zbierz_dane_o_mp3("też_do_zrobienia")
zbierz_dane_o_mp3("jeszcze_do_zrobienia")
```

**Comment by Bialka** [comment]
Okej, rozumiem.

**Comment by Cosiek** [comment]
To upewnij się, że działa, skomituj i wypchnij.

**Comment by Bialka** [comment]
Już.
