### ISSUE TITLE
Zapis danych do pliku.

### ISSUE THREAD

**Issue by Cosiek** [Bialka/cokolwiek#9]
Trochę to trwało, ale będzie kolejny issue.

Teraz chcę, żebyś wzięła ten słownik, który generuje Ci funkcja `zbierz_dane_o_mp3` i zapisała jego klucze do pliku. Już tłumaczę.

Słownik ma klucze, do których przypisane są wartości - `slownik[klucz] = wartosc`. Będzie Ci się zdarzało, że będziesz potrzebowała przeiterować (wykorzystać w petli) po kluczach, albo wartościach, albo ich parach. Przepisz sobie ten kod do pliku i zobacz jak to działa:
```python
slownik = {'klucz1': 1, 'klucz2': 2, 'klucz3': 3}

print("Iteracja po kluczach")
for klucz in slownik.keys():
    print(klucz)
    
print("Iteracja po wartościach")
for wartosc in slownik.values():
    print(wartosc)
    
print("Iteracja po parach (wariant1)")
for para in slownik.items():
    print(para)
    
print("Iteracja po parach (wariant2)")
for klucz, wartosc in slownik.items():
    print(klucz, wartosc)
```

Kolejnym elementem jest zapis do pliku. Żeby coś zapisać do pliku, trzeba go najpierw otworzyć w programie. Do tego służy funkcja `open`, która przyjmuje dwa parametry - nazwę (ściślej mówiąc to ścieżkę do pliku) i tryb w jakim plik został otwarty. Tobie potrzebny będzie jedynie tryb 'w'. Ta funkcja zwróci Ci obiekt pliku, który ma kilka metod (metoda to funkcja powiązana z jakimś obiektem), między innymi metodę `write`, służącą do zapisu. Na koniec trzeba plik zamknąć.
Będzie to wyglądało z grubsza tak:
```
f = open('cokolwiek.txt', 'w')
f.write('pierwsza linijka' + '\n')
f.write('druga linijka' + '\n')
f.close()
```

Czego oczekuję od Ciebie:
 - utwórz nową funkcję w której...
   - otwórz plik
   - przeiteruj po kluczach słownika
   - zapisz każdy klucz do pliku w nowej linijce
   - zamknij plik
 - wywołaj funkcję w bloku `if __name__ == "__main__":` przekazując do niej `slownik` jako argument.

**Comment by Bialka** [comment]
Możesz jeszcze raz wyjaśnić o co chodzi z tymi kluczami i iterowaniem? Rozumiem, że słownik ma klucze do których przypisuje się wartości. Tylko co to za klucze i wartości? I do czego są?

**Comment by Cosiek** [comment]
> Tylko co to za klucze i wartości?

W przypadku twojego słownika, kluczami są nazwy katalogów, a wartościami są listy nazw plików mp3 w tych katalogach.

> I do czego są?

W zależności od potrzeby. Ogólnie do przetrzymywania danych w uporządkowanej strukturze, którą można łatwo obrabiać - np. iterować po niej.

Co do samej iteracji - masz powyżej przykłady. Najlepiej jest je sobie uruchomić i sprawdzić jak się zachowują. Po prostu musisz zastąpić printy właściwym kodem, żeby zapisać linijkę do pliku.

**Comment by Bialka** [comment]
Okej, chyba rozumiem.

**Comment by Bialka** [comment]
```
f = open('cokolwiek.txt', 'w')
f.write('pierwsza linijka' + '\n')
f.write('druga linijka' + '\n')
f.close()
```
A o co chodzi tu z tym plikiem cokolwiek.txt, mam go utworzyć? I z tymi linijkami i '\n'?

**Comment by Cosiek** [comment]
Jeśli plik będzie istniał w momencie kiedy program będzie wykonywał instrukcję `f.write('pierwsza linijka' + '\n')`, to go nadpiszesz. Jeśli nie będzie istniał w tym momencie, to go utworzysz. Krótko mówiąc nie musisz się tym przejmować.

`"\n"` - ten tekst jest interpretowany jako "znak nowej linii" (enter po ludzku). Bez tego wszystko wpisze Ci się w pierwszej linijce pliku.

Spróbuj to:
```
print('abcdef')
print('----------')
print('abc\ndef')
print('----------')
print('\n' * 10)
print('----------')
```

**Comment by Cosiek** [comment]
Na jakim systemie teraz działasz? Winda czy pingwin?

**Comment by Bialka** [comment]
Dalej wind, bo nie ogarnęłam sobie pendrive'a. Mam jeden, ale ma tylko 1 GB, a są potrzebne 1,2 jeśli dobrze pamiętam.

**Comment by Bialka** [comment]
```
def iterowanie():
    f = open('cokolwiek.txt', 'w')
    slownik = {'klucz1': 1, 'klucz2': 2, 'klucz3': 3}

    print('Iteracja po kluczch')
    for klucz in slownik.key():
        print(klucz)
    f.write('pierwsza linijka' + '\n')

    print('Iteracja po wartościach')
    for wartosc in slownik.values():
        print(wartosc)
    f.write('druga linijka' + '\n')

    print('Iteracja po parach (wariant1)')
    for para in slownik.items():
        print(para)
    f.write('trzecia linijka' + '\n')

    print('Interacja po parach (wariant2)')
    for klucz, wartosc in slownik.items():
        print(klucz, wartosc)
    f.write('czwarta linijka' + '\n')
    f.close()
    return  


def zbierz_dane_o_mp3(katalog):
    slownik = {}
    licznik_plikow = 0
    licznik_katalogow = 0
    for x in os.walk(katalog):
        nowa_lista = []
        for nazwa_pliku in x[2]:
            if nazwa_pliku.endswith(".mp3"):
                nowa_lista.append(nazwa_pliku)
                licznik_plikow += 1
        if nowa_lista:
            slownik[(x[0])] = nowa_lista
            licznik_katalogow += 1
    print("Znaleziono {} plików w {} katalogach.".format(licznik_plikow, licznik_katalogow))
    return slownik


print("Zaczynam")
print (iterowanie)
if __name__ == "__main__":
    slownik = zbierz_dane_o_mp3("do_zrobienia")          
    print(slownik)
```

I jak to wygląda? Wynik daje taki:

```
Zaczynam
<function iterowanie at 0x00713540>
Znaleziono 42 plików w 9 katalogach.
{'do_zrobienia\\1\\1.1': ['01 Areta Niwa.mp3', '02 Yuka no Waga Ie (movie version.mp3', '04 Doll House (instrumental).mp
3', '05 Shou no Kanashimi (instrumenta.mp3'], 'do_zrobienia\\4': ['01 Fog Bound Klaus Badelt.mp3', '02 The Medallion Cal
ls Klaus Badelt.mp3', '03 The Black Pearl Klaus Badelt.mp3', '04 Will And Elizabeth Klaus Badelt.mp3', '05 Swords Crosse
d Klaus Badelt.mp3', '06 Walk The Plank Klaus Badelt.mp3'], 'do_zrobienia\\5': ['07 Barbossa Is Hungry Klaus Badelt.mp3'
, '08 Blood Ritual Klaus Badelt.mp3', '09 Moonlight Serenade Klaus Badelt.mp3', "10 To The Pirates ' Cave! Klaus Badelt.
mp3", '11 Skull And Crossbones Klaus Badelt.mp3'], 'do_zrobienia\\6': ["12 Bootstrap's Bootstraps Klaus Badelt.mp3", '13
 Underwater March Klaus Badelt.mp3', '14 One Last Shot Klaus Badelt.mp3'], 'do_zrobienia\\1\\1.2': ["06 Arrietty's Song
(instrumental).mp3", '07 Areta Niwa (instrumental).mp3', '08 Shou no Waltz.mp3', '09 Spiller (instrumental).mp3', '10 Am
e (instrumental).mp3'], 'do_zrobienia\\3': ["20 Arrietty's Song.mp3", '21 Boku no Namida.mp3', '22 Goodbye My Friend.mp3
'], 'do_zrobienia\\2\\2.2': ['16 Shou no Uta (instrumental).mp3', '17 Taisetsu na Omoide.mp3', '18 Goodbye My Friend (in
strumenta.mp3', '19 Anata wo Kesshite Wasurenai.mp3'], 'do_zrobienia\\2\\2.1': ['11 The Wild Waltz.mp3', '12 Shou no Kan
ashimi (instrumenta.mp3', '13 Fuan na Kimochi.mp3', '14 Anata to Tomoni.mp3', '15 Seijaku no Yashiki.mp3'], 'do_zrobieni
a\\7': ['01 Sail Locker Basil Poledouris.mp3', '02 Winning Basil Poledouris.mp3', '03 Windward Work Basil Poledouris.mp3
', '04 Downwind Basil Poledouris.mp3', '05 The Break-Up Basil Poledouris.mp3', '06 To Australia Basil Poledouris.mp3', '
07 The Dinghy Race Basil Poledouris.mp3']}
```

**Comment by Cosiek** [comment]
Ok - pierwsza uwaga. `print (iterowanie)` - zrobiłaś print funkcji, ale jej nie wywołałaś. Powinno być `print (iterowanie())` - dopiero wtedy kod funkcji się wykona. Jak dodasz te nawiasy, zaczną się właściwe errory.

Druga uwaga. Nie czytasz uważnie na czym polega zadanie i piszesz jakąś hybrydę kodu, który wpisałem w zadaniu jako przykłady jak coś działa.

> Teraz chcę, żebyś wzięła ten słownik, który generuje Ci funkcja zbierz_dane_o_mp3 i zapisała jego klucze do pliku.
> [...]
> Czego oczekuję od Ciebie:
>  - utwórz nową funkcję w której...
>    - otwórz plik
>    - przeiteruj po kluczach słownika
>    - zapisz każdy klucz do pliku w nowej linijce
>    - zamknij plik
>  - wywołaj funkcję w bloku `if __name__ == "__main__":` przekazując do niej `slownik` jako argument.

Tak w ramach zabawy - spróbuj doprowadzić funkcję `iterowanie` do takiego stanu, żeby działała i zobacz co się stanie.

**Comment by Bialka** [comment]
Zrobione.
